using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GameAPI.Models;

namespace GameAPI.Repositories
{
    public class RatingsRepo
    {
        public List<Rating> GetAllRatings()
        {
            return new List<Rating>
            {
                new Rating(1, 10),
                new Rating(1, 10),
                new Rating(1, 9),
                new Rating(1, 8),
                new Rating(1, 9),
                new Rating(1, 10),
                new Rating(1, 10),
                new Rating(1, 10),
                new Rating(1, 9),
                new Rating(1, 5),
                new Rating(1, 9),
                new Rating(1, 10),

                new Rating(2, 8),
                new Rating(2, 8),
                new Rating(2, 7),
                new Rating(2, 6),
                new Rating(2, 7),
                new Rating(2, 8),
                new Rating(2, 8),
                new Rating(2, 8),
                new Rating(2, 7),
                new Rating(2, 3),
                new Rating(2, 7),
                new Rating(2, 8),

                new Rating(3, 7),
                new Rating(3, 7),
                new Rating(3, 6),
                new Rating(3, 5),
                new Rating(3, 6),
                new Rating(3, 7),
                new Rating(3, 7),
                new Rating(3, 7),
                new Rating(3, 6),
                new Rating(3, 2),
                new Rating(3, 6),
                new Rating(3, 7),

                new Rating(4, 5),
                new Rating(4, 5),
                new Rating(4, 4),
                new Rating(4, 3),
                new Rating(4, 4),
                new Rating(4, 5),
                new Rating(4, 4),
                new Rating(4, 5),
                new Rating(4, 3),
                new Rating(4, 2),
                new Rating(4, 1),
                new Rating(4, 7),

                new Rating(5, 10),
                new Rating(5, 10),
                new Rating(5, 9),
                new Rating(5, 8),
                new Rating(5, 9),
                new Rating(5, 10),
                new Rating(5, 10),
                new Rating(5, 10),
                new Rating(5, 9),
                new Rating(5, 5),
                new Rating(5, 9),
                new Rating(5, 10),

                new Rating(6, 5),
                new Rating(6, 6),
                new Rating(6, 7),
                new Rating(6, 6),
                new Rating(6, 5),
                new Rating(6, 7),
                new Rating(6, 6),
                new Rating(6, 5),
                new Rating(6, 7),
                new Rating(6, 6),
                new Rating(6, 5),
                new Rating(6, 7),

                new Rating(7, 10),
                new Rating(7, 10),
                new Rating(7, 7),
                new Rating(7, 7),
                new Rating(7, 6),
                new Rating(7, 7),
                new Rating(7, 8),
                new Rating(7, 7),
                new Rating(7, 6),
                new Rating(7, 7),
                new Rating(7, 8),
                new Rating(7, 4),

                new Rating(8, 9),
                new Rating(8, 9),
                new Rating(8, 8),
                new Rating(8, 7),
                new Rating(8, 8),
                new Rating(8, 10),
                new Rating(8, 8),
                new Rating(8, 7),
                new Rating(8, 8),
                new Rating(8, 9),
                new Rating(8, 9),
                new Rating(8, 10),

                new Rating(9, 7),
                new Rating(9, 6),
                new Rating(9, 6),
                new Rating(9, 6),
                new Rating(9, 5),
                new Rating(9, 7),
                new Rating(9, 5),
                new Rating(9, 7),
                new Rating(9, 9),
                new Rating(9, 7),
                new Rating(9, 6),
                new Rating(9, 4),

                new Rating(10, 10),
                new Rating(10, 10),
                new Rating(10, 9),
                new Rating(10, 9),
                new Rating(10, 9),
                new Rating(10, 10),
                new Rating(10, 10),
                new Rating(10, 10),
                new Rating(10, 9),
                new Rating(10, 8),
                new Rating(10, 9),
                new Rating(10, 10),
            };
        }
    }
}
